name: CI Test & Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Run tests with coverage
        run: npm test -- --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          fail_ci_if_error: true
      - name: Notify Slack
        if: always()
        env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
        STATUS="${{ job.status }}"
        curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"CI Pipeline *$STATUS* untuk repo ${{ github.repository }}\"}" $SLACK_WEBHOOK_URL
      # Optional: Telegram notification
      # - name: Notify Telegram
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: "CI Pipeline ${{ job.status }} for ${{ github.repository }}"
